name: Dockerhub Build & Deploy CI
description: 'Builds using Docker buildx and deploys using Dockerhub'

inputs:
  dockerhub_username:
    description: 'Username for the Dockerhub account'
    required: true
    
  dockerhub_token:
    description: 'Access token for the Dockerhub account'
    required: true

  build_context:
    description: 'Directory that will be used for the build context'
    required: true

  dockerhub_repo_owner:
    description: 'Dockerhub repository owner. Eg. dockerhub_repo_owner/image_name:image_tag'
    required: true

  image_name:
    description: 'Docker image name. Eg. dockerhub_repo_owner/image_name:image_tag'
    required: true
  
  image_tag:
    description: 'Docker image tag. Eg. dockerhub_repo_owner/image_name:image_tag'
    required: true
    default: "latest"
  
runs:
  using: 'composite'
  steps:
  - name: Set up QEMU
    uses: docker/setup-qemu-action@v3

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3

  - name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ inputs.dockerhub_username }}
      password: ${{ inputs.dockerhub_token }}
      
  - name: Build and push
    uses: docker/build-push-action@v5
    with:
      context: ${{ inputs.build_context }}
      platforms: linux/amd64,linux/arm64
      push: true
      tags: ${{ inputs.dockerhub_repo_owner }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
      cache-from: type=gha
      cache-to: type=gha,mode=max