name: PyTest CI
description: 'Tests a Python application using PyTest and flake8'

inputs:
  python_version:
    description: 'The Python version that the code will be tested with'
    required: true
  
runs:
  using: 'composite'
  steps:
  - name: Set up Python
    uses: actions/setup-python@v3
    with:
      python-version: ${{ inputs.python_version }}

  - name: Install dependencies
    shell: bash
    run: |
      python3 -m pip install --upgrade pip
      python3 -m venv .venv
      source .venv/bin/activate
      pip3 install flake8 pytest pytest-cov mypy flake8-bugbear
      if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi

  - name: Lint with flake8
    shell: bash
    run: |
      source .venv/bin/activate
      # stop the build if there are Python syntax errors or undefined names
      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  - name: Test with pytest
    shell: bash
    run: |
      source .venv/bin/activate
      pytest --cov

  - name: Check Python typing with mypy
    shell: bash
    run: |
      source .venv/bin/activate
      mypy src