name: Python CI Pipeline

on: [push, pull_request]

env:
  DOCKER_IMAGE_NAME: "example_project"
  PYTEST_COVERAGE_FAIL_PERCENT: 50
  PYTEST_COVERAGE_XML_FILE_NAME: "coverage-reports/coverage-pytest.xml"
  PYTHON_APP_SOURCE_DIR: "example_project"
  PYTHON_VERSION: "3.12"
  SONAR_ORGANIZATION: "scottahern"
  SONAR_PROJECT_KEY: "scottahern_action-testing"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Validate conventional commits
      uses: wagoid/commitlint-github-action@v6

    - name: Scan for secrets
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_TOKEN }}

    - name: Run Custom Python CI action
      uses: ./.github/actions/python/
      with: 
        python_version: ${{ env.PYTHON_VERSION }}
        pytest_coverage_xml_file_name: ${{ env.PYTEST_COVERAGE_XML_FILE_NAME }}
        pytest_coverage_fail_percent: ${{ env.PYTEST_COVERAGE_FAIL_PERCENT }}
        source_dir: ${{ env.PYTHON_APP_SOURCE_DIR }}

    - name: Run Custom SonarCloud action
      uses: ./.github/actions/sonarcloud/
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        sonar_token: ${{ secrets.SONAR_TOKEN }}
        pytest_coverage_xml_file_name: ${{ env.PYTEST_COVERAGE_XML_FILE_NAME }}
        sonar_args: >
          -D sonar.organization=${{ env.SONAR_ORGANIZATION }}
          -D sonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
          -D sonar.exclusions=${{ env.PYTHON_APP_SOURCE_DIR }}/.venv/**
          -D sonar.python.coverage.reportPaths=${{ env.PYTEST_COVERAGE_XML_FILE_NAME }}
          -D sonar.sources=${{ env.PYTHON_APP_SOURCE_DIR }}

    - name: Run Custom Docker action
      uses: ./.github/actions/docker/
      with: 
        dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
        build_context: ${{ env.PYTHON_APP_SOURCE_DIR }}
        docker_image_name: ${{ env.DOCKER_IMAGE_NAME }}
        github_token: ${{ secrets.GITHUB_TOKEN }}