name: Python CI Pipeline

on: [push, pull_request]

env:
  # needed for converting pytest coverage to sonarcloud formatting, details here:
  # https://copdips.com/2023/01/sonarcloud-github-action.html#file-githubworkflowsciyml
  pytest_coverage_xml_file_name: "coverage-reports/coverage-pytest.xml"
  source_dir: "src/python_app"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Validate conventional commits
      uses: wagoid/commitlint-github-action@v6

    - name: Scan for secrets
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_TOKEN }}

    - name: Run Custom Python CI action
      uses: ./.github/actions/python/
      with: 
        python_version: "3.10"
        pytest_coverage_xml_file_name: ${{ env.pytest_coverage_xml_file_name }}
        pytest_coverage_fail_percent: 50
        source_dir: ${{ env.source_dir }}

    - name: Run Custom SonarCloud action
      uses: ./.github/actions/sonarcloud/
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        sonar_token: ${{ secrets.SONAR_TOKEN }}
        pytest_coverage_xml_file_name: ${{ env.pytest_coverage_xml_file_name }}
        sonar_args: >
          -D sonar.organization=scottahern
          -D sonar.projectKey=scottahern_action-testing
          -D sonar.exclusions=${{ env.source_dir }}/.venv/**
          -D sonar.python.coverage.reportPaths=${{ env.pytest_coverage_xml_file_name }}
          -D sonar.sources=${{ env.source_dir }}

    - name: Run Custom Dockerhub action
      uses: ./.github/actions/dockerhub/
      with: 
        dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
        build_context: "${{ env.source_dir }}"
        dockerhub_repo_owner: ${{ secrets.DOCKERHUB_USERNAME }}
        image_name: "test-python-project"
        image_tag: "latest"