name: Python CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu:latest
    steps:
    - name: Run Custom SonarCloud action
      uses: ./.github/actions/sonarcloud_action.yml
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        sonar_token: ${{ secrets.SONAR_TOKEN }}
        sonar_args: >
          -D sonar.organization=mo0nmann
          -D sonar.projectKey=mo0nmann_git-actions-test-node

    - name: Run Custom PyTest action
      uses: ./.github/actions/pytest_action.yml
      with: 
        python_version: "3.10"

    - name: Run Custom PyTest action
      uses: ./.github/actions/dockerhub_action.yml
      with: 
        dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
        build_context: "src"
        dockerhub_repo_owner: ${{ secrets.DOCKERHUB_USERNAME }}
        image_name: "test-python-project"
        image_tag: "latest"